<?php

namespace P4\BilletterieBundle\Repository;

use Doctrine\ORM\Query\ResultSetMapping;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
	
}
