p4_billetterie_homepage:
    path:     /
    defaults:
      _controller: P4BilletterieBundle:Booking:index

p4_billetterie_recap:
    path:     /booking
    defaults:
      _controller: P4BilletterieBundle:Booking:recap
    # requirements:
    #     id: \d+
        
p4_billetterie_test:
    path:     /test
    defaults:
      _controller: P4BilletterieBundle:Booking:test

p4_billetterie_checkout:
    path:     /checkout
    defaults:
      _controller: P4BilletterieBundle:Booking:checkout      

p4_billetterie_payment:
    path:     /payment
    defaults:
      _controller: P4BilletterieBundle:Booking:payment