services:

  p4_billetterie.ageprix_visitor:
      class: P4\BilletterieBundle\AgePrix\AgePrixVisitor
      arguments:
        - %tarifgratuit%
        - %tarifenfant%
        - %tarifnormal%
        - %tarifsenior%
        - %tarifpreferentiel%

  p4_billetterie.email.recap_mailer:
      class: P4\BilletterieBundle\Email\RecapMailer
      arguments:
          - "@mailer"
          - "@templating"        



